spring:
  cloud:
    stream:
      binders:
        kafka-plain:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: 127.0.0.1:9093
            autoAddPartitions: true
            autoCreateTopics: true
            configuration:
              security.protocol: SASL_PLAINTEXT
              sasl.mechanism: PLAIN
              sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"test\" password=\"testtest\";"
      bindings:
        customerConsumer:
          binder: kafka-plain
          group: Customer.Group
          destination: topic.customer
        customerProducer:
          binder: kafka-plain
          destination: topic.customer
logging:
  level.root: INFO
  level.com.tirmizee: INFO
  org.springframework: INFO
  org:
    apache:
      kafka:
        clients: WARNING